# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Coverage

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:

  coverage:
    runs-on: ubuntu-latest
    name: coverage

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Test with pytest
      run: |
        tox -e py39-coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      continue-on-error: true
      with:
        fail_ci_if_error: true
        files: ./coverage.xml
        verbose: true
